// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	migrator "github.com/maxkimambo/pd/internal/migrator"
	mock "github.com/stretchr/testify/mock"
)

// MockDiskMigratorInterface is an autogenerated mock type for the DiskMigratorInterface type
type MockDiskMigratorInterface struct {
	mock.Mock
}

type MockDiskMigratorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiskMigratorInterface) EXPECT() *MockDiskMigratorInterface_Expecter {
	return &MockDiskMigratorInterface_Expecter{mock: &_m.Mock}
}

// MigrateInstanceDisks provides a mock function with given fields: ctx, migration
func (_m *MockDiskMigratorInterface) MigrateInstanceDisks(ctx context.Context, migration *migrator.InstanceMigration) error {
	ret := _m.Called(ctx, migration)

	if len(ret) == 0 {
		panic("no return value specified for MigrateInstanceDisks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *migrator.InstanceMigration) error); ok {
		r0 = rf(ctx, migration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDiskMigratorInterface_MigrateInstanceDisks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrateInstanceDisks'
type MockDiskMigratorInterface_MigrateInstanceDisks_Call struct {
	*mock.Call
}

// MigrateInstanceDisks is a helper method to define mock.On call
//   - ctx context.Context
//   - migration *migrator.InstanceMigration
func (_e *MockDiskMigratorInterface_Expecter) MigrateInstanceDisks(ctx interface{}, migration interface{}) *MockDiskMigratorInterface_MigrateInstanceDisks_Call {
	return &MockDiskMigratorInterface_MigrateInstanceDisks_Call{Call: _e.mock.On("MigrateInstanceDisks", ctx, migration)}
}

func (_c *MockDiskMigratorInterface_MigrateInstanceDisks_Call) Run(run func(ctx context.Context, migration *migrator.InstanceMigration)) *MockDiskMigratorInterface_MigrateInstanceDisks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*migrator.InstanceMigration))
	})
	return _c
}

func (_c *MockDiskMigratorInterface_MigrateInstanceDisks_Call) Return(_a0 error) *MockDiskMigratorInterface_MigrateInstanceDisks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDiskMigratorInterface_MigrateInstanceDisks_Call) RunAndReturn(run func(context.Context, *migrator.InstanceMigration) error) *MockDiskMigratorInterface_MigrateInstanceDisks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDiskMigratorInterface creates a new instance of MockDiskMigratorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiskMigratorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiskMigratorInterface {
	mock := &MockDiskMigratorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
